### ISSUE TITLE
7.1 truecrypt-verified won't install on OSX 10.10

### ISSUE THREAD

**Issue by grisutheguru** [AuditProject/truecrypt-verified-mirror#1]
Ahoi!

Thanks for the new version, I tried it on 10.10 beta but it won't install.
I think this is done by the version checker within the installer and it says "you need 10.4 or greater to install".
Maybe this can be changed to be able to install on 10.10.

**Comment by grisutheguru** [comment]
Additional comment:
I opened the packed and installed to containing packages which worked fine, so Truecrypt seems to run on 10.10.
It should just depend on the installer.

**Comment by JedediahShine** [comment]
Perfect solution!
Works fine, thank you!

**Comment by grisutheguru** [comment]
As truecrypt seems not to be updated anymore, I leave this as it is and close the issue
