### ISSUE TITLE
not usable for developers

### ISSUE THREAD

**Issue by DerKnerd** [AuditProject/truecrypt-verified-mirror#2]
Would you please put the code in as git repo and not as tarball?

**Comment by Zensin** [comment]
Absolutely no community contribution going on and this is one reason. TC has some problems that have been identified in the audit but not patched that I'm aware of. It's been a long time now where they're like "Okay here are some bugs but we're not going to do anything to facilitate fixing them." Nonsensical. TC is awesome. Let's facilitate patching anything that needs to be patched.

**Comment by neandrake** [comment]
This repository is named "truecrypt verified mirror". This purpose of this repo is to create a verified snapshot of the last version of truecrypt, not continued community development.

See these other projects that are forked from this last version of truecrypt:
https://github.com/veracrypt/VeraCrypt
https://github.com/CipherShed/CipherShed
